CREATE TABLE EPL 
(
  HOME_TEAM VARCHAR2(50) NOT NULL, 
  AWAY_TEAM VARCHAR2(50) NOT NULL, 
  HOME_GOALS NUMBER NOT NULL,
  AWAY_GOALS NUMBER NOT NULL,
  RESULTS CHAR NOT NULL,
  SEASON VARCHAR2(9) NOT NULL, 
  CONSTRAINT EPL_PK PRIMARY KEY 
  (
    HOME_TEAM, 
	AWAY_TEAM, 
	SEASON 
  )
  ENABLE 
);
