--Query 1
SELECT
    TEAM, sum(GOALS)
        FROM (SELECT "EPL".HOME_TEAM as TEAM, sum("EPL".HOME_GOALS) as GOALS from EPL 
        GROUP BY "EPL".HOME_TEAM
        UNION
        SELECT "EPL".AWAY_TEAM as TEAM, sum("EPL".AWAY_GOALS) as GOALS from EPL 
        GROUP BY "EPL".AWAY_TEAM)
GROUP BY TEAM
ORDER BY sum(GOALS) DESC;

--Query 2
SELECT count(*) FROM "EPL"
GROUP BY "EPL".RESULTS;

--Query 3
SELECT "EPL".SEASON, count(*) FROM "EPL"
WHERE "EPL".RESULTS = 'H'
GROUP BY "EPL".SEASON
ORDER BY "EPL".SEASON;
