--Query 1
SELECT
    TEAM, sum(GOALS)
        FROM (SELECT MATCH.TEAM_HOME_NAME as TEAM, sum(MATCH.MATCH_HOME_GOALS) as GOALS from MATCH 
        GROUP BY MATCH.TEAM_HOME_NAME
        UNION
        SELECT MATCH.TEAM_AWAY_NAME as TEAM, sum(MATCH.MATCH_AWAY_GOALS) as GOALS from MATCH 
        GROUP BY MATCH.TEAM_AWAY_NAME)
GROUP BY TEAM
ORDER BY sum(GOALS) DESC;

--Query 2
SELECT MATCH.MATCH_RESULTS, count(*) FROM MATCH
GROUP BY MATCH.MATCH_RESULTS;

--Query 3
SELECT MATCH.SEASON_PERIOD, count(*) FROM MATCH
WHERE MATCH.MATCH_RESULTS = 'D'
GROUP BY MATCH.SEASON_PERIOD
ORDER BY MATCH.SEASON_PERIOD;

